### ISSUE TITLE
Error: "Cannot read property 'treeBaseDuration' of undefined"

### ISSUE THREAD

**Issue by jstejada** [bvaughn/react-devtools-experimental#267]
This happened when I clicked on a commit while browsing a profile I recorded

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.0-a04dbd0

Call stack: at chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:56:271235
    at Object.useMemo (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:61084)
    at useMemo (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:30:5137)
    at qi (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:56:271194)
    at Ia (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:56417)
    at ci (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:63273)
    at xl (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:96620)
    at vl (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:81540)
    at Al (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:79166)
    at e (chrome-extension://akkpaehpnolchhkkfbedcdcikfdnjobk/build/main.js:43:77886)

Component stack: in qi
    in div
    in t
    in div
    in $i
    in Suspense
    in div
    in div
    in div
    in us
    in di
    in Unknown
    in Ga
    in Unknown
    in div
    in div
    in hi
    in Pe
    in We
    in Os

**Comment by bvaughn** [comment]
Can you attach a (JSON) export of the profiling data? Or otherwise share something about the app you were profiling?

**Comment by lucasecdb** [comment]
I've just ran into this as well. I tried saving the profiling data but the button isn't doing anything :-(

**Comment by bvaughn** [comment]
> I tried saving the profiling data but the button isn't doing anything 

Unfortunately there's a Chrome bug where the download API doesn't seem to work until you've undocked the extension from the browser 😦  I've let them know about it.
