### ISSUE TITLE
Error: "Could not find commit data for root "1""

### ISSUE THREAD

**Issue by daltondowning** [bvaughn/react-devtools-experimental#285]
STR:

1. Open an app that supports profiling. I used https://react-window.now.sh/#/examples/list/fixed-size.
2. Open React DevTool Profiler.
3. Click the "Reload and start profiling" button.
4. Click the "Stop profiling" button.
5. Click the "Reload and start profiling" button again.

![react_devtools_error](https://user-images.githubusercontent.com/18369969/58276435-70d9c680-7d65-11e9-9176-de886e2f80c1.gif)

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.0-f47b40f

Call stack: at k.getDataForRoot (chrome-extension://enlgfgbjejkjjdhgcccmjjllcfofkimb/build/main.js:1:27280)
    at es (chrome-extension://enlgfgbjejkjjdhgcccmjjllcfofkimb/build/main.js:56:282337)
    at Ia (chrome-extension://enlgfgbjejkjjdhgcccmjjllcfofkimb/build/main.js:43:56417)
    at ci (chrome-extension://enlgfgbjejkjjdhgcccmjjllcfofkimb/build/main.js:43:63273)
    at xl (chrome-extension://enlgfgbjejkjjdhgcccmjjllcfofkimb/build/main.js:43:96620)
    at vl (chrome-extension://enlgfgbjejkjjdhgcccmjjllcfofkimb/build/main.js:43:81540)
    at gl (chrome-extension://enlgfgbjejkjjdhgcccmjjllcfofkimb/build/main.js:43:79166)
    at ao (chrome-extension://enlgfgbjejkjjdhgcccmjjllcfofkimb/build/main.js:43:41238)
    at R (chrome-extension://enlgfgbjejkjjdhgcccmjjllcfofkimb/build/main.js:56:2133)
    at L (chrome-extension://enlgfgbjejkjjdhgcccmjjllcfofkimb/build/main.js:56:2649)

Component stack: in es
    in div
    in div
    in div
    in mi
    in Unknown
    in ei
    in Unknown
    in div
    in div
    in gi
    in X
    in le
    in Na
    in Ls

**Comment by bvaughn** [comment]
Thanks for the bug report! Fixed in 408fbee
