### ISSUE TITLE
Error: "getCommitTree(): Unable to reconstruct tree for root "1" and commit 129"

### ISSUE THREAD

**Issue by lucasecdb** [bvaughn/react-devtools-experimental#290]
I was just passing through the commits in the profiler, with no node selected. I'll see if I can get a stable repro case for this.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.0-408fbee

Call stack: at b (chrome-extension://ndojpbfkokmodkcdmgpbgfjaogmhdlem/build/main.js:1:17544)
    at x.getCommitTree (chrome-extension://ndojpbfkokmodkcdmgpbgfjaogmhdlem/build/main.js:1:19834)
    at oi (chrome-extension://ndojpbfkokmodkcdmgpbgfjaogmhdlem/build/main.js:56:250066)
    at ya (chrome-extension://ndojpbfkokmodkcdmgpbgfjaogmhdlem/build/main.js:43:54032)
    at ei (chrome-extension://ndojpbfkokmodkcdmgpbgfjaogmhdlem/build/main.js:43:60954)
    at _l (chrome-extension://ndojpbfkokmodkcdmgpbgfjaogmhdlem/build/main.js:43:93376)
    at pl (chrome-extension://ndojpbfkokmodkcdmgpbgfjaogmhdlem/build/main.js:43:80068)
    at fl (chrome-extension://ndojpbfkokmodkcdmgpbgfjaogmhdlem/build/main.js:43:77229)
    at ro (chrome-extension://ndojpbfkokmodkcdmgpbgfjaogmhdlem/build/main.js:43:41211)
    at to (chrome-extension://ndojpbfkokmodkcdmgpbgfjaogmhdlem/build/main.js:43:41116)

Component stack: in oi
    in div
    in div
    in div
    in _a
    in Unknown
    in sa
    in Unknown
    in div
    in div
    in xa
    in X
    in le
    in jo
    in $l

**Comment by bvaughn** [comment]
Any chance you've seen this one again or was it a fluke? I've done a good bit of profiling and haven't seen this error myself.

**Comment by lucasecdb** [comment]
haven't seen it again, but I didn't do much profiling since then. I could try to profile my app again later to see if it happens, but I guess we can close this for now

**Comment by bvaughn** [comment]
K! If one of us (or someone else) sees it again, let's re-open with hopefully some more repro info.
